<?php

namespace Hillpy\HikSDK\InfovisionIoT\Params;

class FaceParam
{
    public static $face = [
        'getPersonFaceByAttr' => [],
        'getPersonFaceByAttrV1' => [],
        'getFaceByImageModel' => [],
        'getFaceByImageModelV1' => [],
        'getFaceDataByAttr' => [],
        'getFaceDataByImageModel' => [],
        'getFaceDataByImageModelV1' => [],
        'submitGetFaceDataTaskByModel' => [],
        'getFaceFataByTaskWithPage' => [],
        'getFaceRecordById' => [],
        'submitGetFaceOccurFrequenceTask' => [],
        'getFaceOccurFrequenceByTaskIdWithPage' => [],
        'getFaceOccurFrequenceByGroupIdWithPage' => [],
        'submitGetFaceOccurTogetherTask' => [],
        'getFaceOccurTogetherByTaskWithPage' => [],
        'getFaceOccurTogetherByGroupIdWithPage' => [],
        'submitGetFaceOccurCollisionTask' => [],
        'getFaceOccurCollisionByTaskWithPage' => [],
        'getFaceOccurCollisionByGroupIdWithPage' => [],
        'submitFacePersonLibsOccurCollisionTask' => [],
        'getFacePersonLibsOccurCollisionByTaskWithPage' => [],
        'getFaceStatisticsTotalNumByTime' => [],
        'getFaceStatisticsTotalNumByTimeV1' => [],
        'getPersonLib' => [],
        'getPersonLibV1' => [],
        'addPersonLib' => [],
        'modifyPersonLib' => [],
        'deletePersonLib' => [],
        'deletePersonLibV1' => [],
        'addPerson' => [],
        'addPersonV1' => [],
        'modifyPerson' => [],
        'modifyPersonV1' => [],
        'deletePerson' => [],
        'deletePersonV1' => [],
        'moveLib' => [],
        'moveLibV1' => [],
        'addSinglePictureControl' => [],
        'modifySinglePictureControl' => [],
        'addPersonLibControl' => [],
        'modifyPersonLibControl' => [],
        'getPersonControlWithPage' => [],
        'addSinglePictureRegionControl' => [],
        'modifySinglePictureRegionControl' => [],
        'addPersonLibRegionControl' => [],
        'modifyPersonLibRegionControl' => [],
        'getFaceAlarmRecordsWithPage' => [],
        'getFaceAlarmRecordsWithPageV1' => [],
        'getPersonControlsDetailsWithPage' => [],
    ];
}
