<?php

namespace Hillpy\HikSDK\InfovisionIoT\Params;

class VehicleParam
{
    public static $vehicle = [
        'getVehicleByImageModel' => [],
        'getVehicleByAttrWithPage' => [],
        'getTracksByVehicleWithPage' => [],
        'submitVehicleFeaturesJobTask' => [],
        'getVehicleCompareResultGroupByTaskIdWithPage' => [],
        'getVehicleCompareResultByTaskIdWithPage' => [],
        'getVehicleByDimension' => [],
        'getAccompanyVehiclesWithPage' => [],
        'getVehiclesByTrackWithPage' => [],
        'getVehiclesByTimeTrackWithPage' => [],
        'getVehiclesByFrequenceWithPage' => [],
        'getHideVehiclesWithPage' => [],
        'getVehiclesPlateFakedWithPage' => [],
        'getVehiclesFirstInCityWithPage' => [],
        'getNightVehiclesWithPage' => [],
        'getVehicleStatisticsByGroupWithPage' => [],
        'getVehicleStatisticsByGroupWithPageV1' => [],
        'addVehicleControl' => [],
        'updateVehicleControl' => [],
        'getVehicleDeployResultWithPage' => [],
        'getVehicleAlarmRecordsWithPage' => [],
        'addVehicleNameListControl' => [],
        'modifyVehicleNameListControl' => [],
        'getVehicleNameListDeployResultWithPage' => [],
        'getVehicleNameListAlarmRecordsWithPage' => [],
        'addVehicleModelControl' => [],
        'modifyVehicleModelControl' => [],
        'getVehicleModelDeployResultWithPage' => [],
        'getVehicleModelAlarmRecordsWithPage' => [],
        'getVehicleLib' => [],
        'getVehicleLibV3' => [],
        'addVehicleLib' => [],
        'addVehicleLibV3' => [],
        'modifyVehicleLib' => [],
        'modifyVehicleLibV3' => [],
        'deleteVehicleLib' => [],
        'deleteVehicleLibV3' => [],
        'getVehicle' => [],
        'addVehicle' => [],
        'addVehicleV3' => [],
        'modifyVehicle' => [],
        'modifyVehicleV3' => [],
        'deleteVehicle' => [],
        'deleteVehicleV3' => [],
    ];
}
